// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD13Xn8C-7-eT3ZSRtU0NZjAVrexjfgqt0',
    appId: '1:993935550987:web:4ff5f1de488bee6401350e',
    messagingSenderId: '993935550987',
    projectId: 'hotel-46c62',
    authDomain: 'hotel-46c62.firebaseapp.com',
    storageBucket: 'hotel-46c62.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDH8pSb4tHHCIjmHXIXR33WV-szZpBzlwg',
    appId: '1:993935550987:android:494f625bd8d0a17c01350e',
    messagingSenderId: '993935550987',
    projectId: 'hotel-46c62',
    storageBucket: 'hotel-46c62.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvE2KLCqkrNpZea2k7Rw7aWwugz48cHMk',
    appId: '1:993935550987:ios:99a48b926ae72ad301350e',
    messagingSenderId: '993935550987',
    projectId: 'hotel-46c62',
    storageBucket: 'hotel-46c62.appspot.com',
    iosBundleId: 'com.example.flutterApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBvE2KLCqkrNpZea2k7Rw7aWwugz48cHMk',
    appId: '1:993935550987:ios:99a48b926ae72ad301350e',
    messagingSenderId: '993935550987',
    projectId: 'hotel-46c62',
    storageBucket: 'hotel-46c62.appspot.com',
    iosBundleId: 'com.example.flutterApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD13Xn8C-7-eT3ZSRtU0NZjAVrexjfgqt0',
    appId: '1:993935550987:web:e0fa3de5b65bf5fe01350e',
    messagingSenderId: '993935550987',
    projectId: 'hotel-46c62',
    authDomain: 'hotel-46c62.firebaseapp.com',
    storageBucket: 'hotel-46c62.appspot.com',
  );
}
